[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.42.1"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "8fb92bf14e22a6106d25dd82160ea51fe5cd6b15"}
